### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by LinBoyook** [first19326/Hexo-LiveForCode#1]
Why is there a typeError which shows “Cannot read property 'LongCang' of undefined” when I “hexo g” ？

**Comment by first19326** [comment]
> 为什么有一个类型Error显示"无法读取属性'龙仓'的未定义"，当我"hexo g"？

Thank you very much for your feedback, and I'm really sorry for replying to you so late. As for the question you submitted, I hope you can upload a screenshot of this question, so that I can locate the specific location of the question. Thank you.

**Comment by first19326** [comment]
> Why is there a typeError which shows “Cannot read property 'LongCang' of undefined” when I “hexo g” ？

Thank you very much for your feedback, and I'm really sorry for replying to you so late. As for the question you submitted, I hope you can upload a screenshot of this question, so that I can locate the specific location of the question. Thank you.

**Comment by LinBoyook** [comment]
There are many errors of this kind：
![2020-10-05_163728](https://user-images.githubusercontent.com/36160965/95057828-43f33d00-0729-11eb-8ef3-a9f18ac3fbde.png)

**Comment by first19326** [comment]
> There are many errors of this kind：
> ![2020-10-05_163728](https://user-images.githubusercontent.com/36160965/95057828-43f33d00-0729-11eb-8ef3-a9f18ac3fbde.png)

After looking at your screenshot, I would like you to confirm whether the Font configuration in _config.yml configuration file under LiveForCode theme folder has been changed or deleted.

**Comment by LinBoyook** [comment]
I could find the Font configuration in the config.yml configuration in the themes/LiveCode/LiveForCode/_config.yml file, and I'm sure it never be changed.
![2020-10-05_233151](https://user-images.githubusercontent.com/36160965/95100196-702baf80-0763-11eb-953f-96989500e69a.png)

**Comment by first19326** [comment]
> I could find the Font configuration in the config.yml configuration in the themes/LiveCode/LiveForCode/_config.yml file, and I'm sure it never be changed.
> ![2020-10-05_233151](https://user-images.githubusercontent.com/36160965/95100196-702baf80-0763-11eb-953f-96989500e69a.png)

I have no clue about your question at present, so I can only guess the cause of the problem and then try. So I want you to provide the version of the hexo, and then run the `hexo g --debug` and paste the trace log. Thank you

**Comment by first19326** [comment]
> I could find the Font configuration in the config.yml configuration in the themes/LiveCode/LiveForCode/_config.yml file, and I'm sure it never be changed.
> ![2020-10-05_233151](https://user-images.githubusercontent.com/36160965/95100196-702baf80-0763-11eb-953f-96989500e69a.png)

I have no clue about your question at present, so I can only guess the cause of the problem and then try. So I want you to provide the version of the hexo, and then run the `hexo g --debug` and paste the trace log. Thank you.

**Comment by naokeziteng** [comment]
> Why is there a typeError which shows “Cannot read property 'LongCang' of undefined” when I “hexo g” ？

If you clone the code directly, you will find that there is a folder named “LiveForCode” inside the folder “LiveForCode”. This folder is the content of the theme you need. I hope you can understand my expression because I just Encountered the same error and solved it.

**Comment by first19326** [comment]
@naokeziteng I can understand what you mean. When you clone the code to `LiveForCode` folder, there will be a `LiveForCode` folder in the folder. In fact, that folder is the main code of the theme, I think this is what you want to express, I will consider adding relevant instructions in the notes. Thanks for your feedback!

**Comment by xyh123456-svg** [comment]
所以，要更改里面文件夹的主题代码吗

**Comment by first19326** [comment]
@xyh123456-svg 这个不需要，上面的问题是说直接将 `Github` 的这个项目 `Copy` 下来的 `Hexo-LiveForCode` 文件夹当成是主题文件夹了，所以正常将其中的 `LiveForCode` 文件夹 `Copy` 出来放到 __Hexo__ 的 `themes` 文件夹下即可，具体操作还是参考 `Readme` 中的教程
