### ISSUE TITLE
jsdelivr挂了，所有样式都没了

### ISSUE THREAD

**Issue by lxy914** [first19326/Hexo-LiveForCode#2]
**jsdelivr挂了，所有样式都没了**

**Comment by planeswalker1205** [comment]
作者你好，关于这个hexo主题的样式都没了  请问近期有修复计划嘛

**Comment by first19326** [comment]
@q314872695 不好意思，刚刚看到。jsDelivr 挂了这件事情我也一直在关注，目前这个 CDN 已经恢复正常，为了保证后续的博客主题正常和稳定，我已经准备了两种配置文件，一份是 CDN 版本，另一份是本地静态文件的版本，可以随意切换。如果今后 CDN 出了问题，可以进行切换，保证网站正常运行。感谢使用本主题，也感谢你的反馈，谢谢。
