### ISSUE TITLE
《Hexo - Live For Code 主题介绍以及使用说明》链接无法打开，链接错了。

### ISSUE THREAD

**Issue by mgxhl** [first19326/Hexo-LiveForCode#3]
您好，新人想使用这个主题，需要阅读使用说明，但点击链接后出现下列错误提示：

访问 www.notes.worstone.cn 的请求遭到拒绝您未获授权，无法查看此网页。
HTTP ERROR 403

----------------------------------------------------------------------------------
后发现正确的链接应该是[https://www.notes.worstone.cn/article/1112885395/](https://www.notes.worstone.cn/article/1112885395/ )。建议更新readme.md的内容。

**Comment by first19326** [comment]
**readme.md** 里面的链接是很久之前的了，多谢提醒，已修改！
